name: GitHub Actions Demo

# Trigger this workflow on pushes to any branch
on: [push]

# A workflow run is made up of one or more jobs
jobs:
  explore-github-actions:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: Say hello world
        run: echo "Hello, world! This job was triggered by a ${{ github.event_name }} event."

      # Runs a set of commands using the runners shell
      - name: List files in the repository
        run: |
          echo "Listing files in the ${{ github.workspace }} repository:"
          ls -F
